<a href="https://colab.research.google.com/github/BALAJIHARIDASAN/Natural-Language-Processing/blob/main/BAG_OF_WORDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import nltk

In [4]:
from  nltk.stem import PorterStemmer

In [5]:
df = pd.read_csv('spam.csv')

In [6]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [8]:
df['spam'] = df.Category.apply(lambda x: 1 if x =='spam' else 0)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size = 0.3)

In [12]:
X_train.shape

(3900,)

In [14]:
X_test.shape

(1672,)

In [15]:
type(X_train)

pandas.core.series.Series

In [18]:
X_train[:4]

1883                     Sorry, I can't help you on this.
4185    I just really need shit before tomorrow and I ...
1991    HI DARLIN IVE JUST GOT BACK AND I HAD A REALLY...
148     Ummma.will call after check in.our life will b...
Name: Message, dtype: object

In [20]:
y_train.head()

1883    0
4185    0
1991    0
148     0
4594    0
Name: spam, dtype: int64

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
v = CountVectorizer()

In [26]:
X_train_cv= v.fit_transform(X_train.values)

In [28]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
v.get_feature_names_out()[1332]

'body'

In [31]:
 v.vocabulary_

{'sorry': 5923,
 'can': 1530,
 'help': 3159,
 'you': 7223,
 'on': 4617,
 'this': 6412,
 'just': 3619,
 'really': 5243,
 'need': 4424,
 'shit': 5705,
 'before': 1216,
 'tomorrow': 6510,
 'and': 903,
 'know': 3703,
 'won': 7103,
 'be': 1188,
 'awake': 1095,
 'like': 3848,
 'hi': 3185,
 'darlin': 2022,
 'ive': 3521,
 'got': 2974,
 'back': 1122,
 'had': 3063,
 'nice': 4463,
 'night': 4471,
 'thanks': 6367,
 'so': 5876,
 'much': 4343,
 'for': 2734,
 'the': 6378,
 'lift': 3842,
 'see': 5598,
 'xxx': 7179,
 'ummma': 6670,
 'will': 7050,
 'call': 1507,
 'after': 794,
 'check': 1647,
 'in': 3396,
 'our': 4679,
 'life': 3838,
 'begin': 1221,
 'from': 2808,
 'qatar': 5155,
 'pls': 4914,
 'pray': 5019,
 'very': 6815,
 'hard': 3102,
 'it': 3509,
 'ok': 4600,
 'wun': 7163,
 'angry': 907,
 'msg': 4325,
 'aft': 793,
 'come': 1790,
 'home': 3234,
 'tonight': 6517,
 'dis': 2184,
 'is': 3497,
 'yijue': 7215,
 'would': 7137,
 'happy': 3101,
 'to': 6487,
 'work': 7117,
 'wif': 7042,
 'all': 853,
 'gek1510'

In [35]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [39]:
X_test_cv = v.transform(X_test)

In [40]:
from sklearn.metrics import classification_report

In [41]:
y_pred = model.predict(X_test_cv)

In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1444
           1       0.96      0.90      0.93       228

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672



In [43]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [44]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [45]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [46]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1444
           1       0.96      0.90      0.93       228

    accuracy                           0.98      1672
   macro avg       0.97      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672

