<a href="https://colab.research.google.com/github/BALAJIHARIDASAN/Natural-Language-Processing/blob/main/NLTK_and_Spacy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import nltk

In [ ]:
from  nltk.stem import PorterStemmer

In [ ]:
import spacy

In [ ]:
model = spacy.load('en_core_web_sm')

In [ ]:
doc = model('Dr.Strange loves pav bajji of mumbai . Hulk loves chaat of delhi')

In [ ]:
for i in doc.sents: # sentence tokenizing
  print(i)

Dr.Strange loves pav bajji of mumbai .
Hulk loves chaat of delhi


In [ ]:
for i in doc.sents:
  for word in i:
    print(word)

Dr.
Strange
loves
pav
bajji
of
mumbai
.
Hulk
loves
chaat
of
delhi


In [ ]:
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
sent_tokenize('Dr.Strange loves pav bajji of mumbai. Hulk loves chaat of delhi')

['Dr.Strange loves pav bajji of mumbai.', 'Hulk loves chaat of delhi']

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
word_tokenize('Dr.Strange loves pav bajji of mumbai. Hulk loves chaat of delhi')

['Dr.Strange',
 'loves',
 'pav',
 'bajji',
 'of',
 'mumbai',
 '.',
 'Hulk',
 'loves',
 'chaat',
 'of',
 'delhi']

In [ ]:
nlp = spacy.blank('en') # tokenizer only

In [ ]:
nlp

In [ ]:
doc = nlp('Dr.Strange loves pav bajji of mumbai. Hulk loves chaat of delhi')

In [ ]:
for i in doc:
  print(i)

Dr.
Strange
loves
pav
bajji
of
mumbai
.
Hulk
loves
chaat
of
delhi


In [ ]:
doc[1]

Strange

In [ ]:
doc[2]

loves

In [ ]:
 doc = nlp('Dr.Strange loves pav bajji of mumbai as it costs only 2$ per plate')

In [ ]:
for i in doc:
  print(i)

Dr.
Strange
loves
pav
bajji
of
mumbai
as
it
costs
only
2
$
per
plate


In [ ]:
# process --  text --> prefix --> exception --> suffix --> exception --> tokenize

In [ ]:
 doc = nlp('''"Let's go to N.Y.!"''' )

In [ ]:
for i in doc:
  print(i)

"
Let
's
go
to
N.Y.
!
"


In [ ]:
token1 = doc[1]

In [ ]:
token1

Let

In [ ]:
type(token1)

spacy.tokens.token.Token

In [ ]:
dir(token1)

['_',
 '__bytes__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 'ancestors',
 'check_flag',
 'children',
 'cluster',
 'conjuncts',
 'dep',
 'dep_',
 'doc',
 'ent_id',
 'ent_id_',
 'ent_iob',
 'ent_iob_',
 'ent_kb_id',
 'ent_kb_id_',
 'ent_type',
 'ent_type_',
 'get_extension',
 'has_dep',
 'has_extension',
 'has_head',
 'has_morph',
 'has_vector',
 'head',
 'i',
 'idx',
 'iob_strings',
 'is_alpha',
 'is_ancestor',
 'is_ascii',
 'is_bracket',
 'is_currency',
 'is_digit',
 'is_left_punct',
 'is_lower',
 'is_oov',
 'is_punct',
 'is_quote',
 'is_right_punct',
 'is_sent_end',
 'is_sent_start',
 'is_space',
 'is_stop',
 'is_title',
 'is_upper',
 'lang',
 'lang_',
 'le

In [ ]:
token1.is_alpha

True

In [ ]:
token1.like_num

False

In [ ]:
token1.text

'Let'

In [ ]:
doc = nlp('Dr.Strange loves pav bajji of mumbai as it costs only 2$ per plate')
for token in doc:
  print(token, token.i, token.is_alpha,token.is_punct,token.like_num,token.is_currency)


Dr. 0 False False False False
Strange 1 True False False False
loves 2 True False False False
pav 3 True False False False
bajji 4 True False False False
of 5 True False False False
mumbai 6 True False False False
as 7 True False False False
it 8 True False False False
costs 9 True False False False
only 10 True False False False
2 11 False False True False
$ 12 False False False True
per 13 True False False False
plate 14 True False False False


In [ ]:
doc = nlp('gimme double cheese extra large healthy pizza')

tokens = [token.text for token in doc]

In [ ]:
tokens

['gimme', 'double', 'cheese', 'extra', 'large', 'healthy', 'pizza']

In [ ]:
for i in doc.sents:
  print(i)

ValueError: ignored

In [ ]:
nlp.pipe_names

[]

In [ ]:
nlp.add_pipe('sentencizer')

In [ ]:
nlp.pipe_names

['sentencizer']

In [ ]:
doc = nlp('Dr.Strange loves pav bajji of mumbai as it costs only 2$ per plate')
for i in doc.sents:
  print(i)

Dr.Strange loves pav bajji of mumbai as it costs only 2$ per plate


In [ ]:
 # nlp pipeline

 # tokenizer --> tagger --> parser --> NER -->

In [ ]:
nlp = spacy.blank('en')
doc = nlp('captain america ate  100$ somosa. then he said i can do this all day')

In [ ]:
for i in doc:
  print(i)

captain
america
ate
 
100
$
somosa
.
then
he
said
i
can
do
this
all
day


In [ ]:
nlp.pipe_names

[]

In [ ]:
nlp = spacy.load('en_core_web_sm')
doc = nlp('captain america ate  100$ somosa. then he said i can do this all day')

In [ ]:
nlp

In [ ]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [ ]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x78d97559fc40>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x78d977a97dc0>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x78d977925230>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x78d97723c080>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x78d9779b3c40>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x78d977924200>)]

In [ ]:
for token in doc:
  print(token,token.pos_,token.lemma_)

captain PROPN captain
america PROPN america
ate VERB eat
  SPACE  
100 NUM 100
$ NOUN $
somosa X somosa
. PUNCT .
then ADV then
he PRON he
said VERB say
i PRON I
can AUX can
do VERB do
this PRON this
all DET all
day NOUN day


In [ ]:
for i in doc.ents:
  print(i.text,i.label_,spacy.explain(i.label_))

100$ MONEY Monetary values, including unit
this all day DATE Absolute or relative dates or periods


In [ ]:
from spacy import displacy

displacy.render(doc,style = 'ent')

'<div class="entities" style="line-height: 2.5; direction: ltr">captain america ate  \n<mark class="entity" style="background: #e4e7d2; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    100$\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">MONEY</span>\n</mark>\n somosa. then he said i can do \n<mark class="entity" style="background: #bfe1d9; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;">\n    this all day\n    <span style="font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; vertical-align: middle; margin-left: 0.5rem">DATE</span>\n</mark>\n</div>'

In [ ]:
df = pd.read_csv('spam.csv')

In [ ]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [91]:
df.Category.value_counts()


ham     4825
spam     747
Name: Category, dtype: int64

In [92]:
df['spam']= df['Category'].apply(lambda x: 1 if x =='spam'else 0)

In [93]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size = 0.2)

In [97]:
from sklearn.feature_extraction.text import CountVectorizer

In [98]:
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)

In [101]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [103]:
v.get_feature_names_out() [1000:1500]

array(['ans', 'ansr', 'answer', 'answered', 'answerin', 'answering',
       'answers', 'answr', 'antha', 'anthony', 'anti', 'antibiotic',
       'any', 'anybody', 'anyhow', 'anymore', 'anyone', 'anyones',
       'anyplaces', 'anythiing', 'anythin', 'anything',
       'anythingtomorrow', 'anytime', 'anyway', 'anyways', 'anywhere',
       'aom', 'apart', 'apartment', 'apes', 'apeshit', 'aphex', 'apo',
       'apologetic', 'apologise', 'apologize', 'app', 'apparently',
       'appear', 'appendix', 'applausestore', 'applebees', 'apples',
       'application', 'apply', 'applyed', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaching',
       'appropriate', 'approve', 'approx', 'apps', 'appt', 'appy',
       'april', 'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking', 'areyouunique', 'argentina',
       'argh', 'argue', 'arguing', 'argumen

In [104]:
   v.vocabulary_

{'yeah': 7738,
 'do': 2396,
 'don': 2425,
 'stand': 6506,
 'to': 7001,
 'close': 1876,
 'tho': 6926,
 'you': 7765,
 'll': 4210,
 'catch': 1708,
 'something': 6374,
 'hi': 3457,
 'my': 4729,
 'email': 2589,
 'address': 828,
 'has': 3374,
 'changed': 1749,
 'now': 4902,
 'it': 3806,
 'is': 3794,
 'if': 3640,
 're': 5657,
 'thinking': 6915,
 'of': 4953,
 'lifting': 4159,
 'me': 4464,
 'one': 5001,
 'then': 6893,
 'no': 4859,
 'thanx4': 6878,
 'today': 7008,
 'cer': 1734,
 'was': 7453,
 'nice': 4835,
 'up': 7248,
 'but': 1603,
 'we': 7476,
 'ave': 1183,
 'find': 2876,
 'more': 4645,
 'time': 6969,
 'often': 4967,
 'oh': 4970,
 'well': 7514,
 'take': 6760,
 'care': 1679,
 'soon': 6389,
 'sorry': 6398,
 'call': 1633,
 'later': 4082,
 'sms': 6335,
 'auction': 1163,
 'have': 3388,
 'won': 7635,
 'nokia': 4866,
 '7250i': 623,
 'this': 6920,
 'what': 7534,
 'get': 3142,
 'when': 7539,
 'win': 7579,
 'our': 5069,
 'free': 3007,
 'part': 5145,
 'send': 6081,
 '86021': 697,
 'hg': 3456,
 'suite342'

In [105]:
X_train_np = X_train_cv.toarray()

In [106]:
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [107]:
np.where(X_train_np[0]!=0)

(array([1708, 1876, 2396, 2425, 4210, 6374, 6506, 6926, 7001, 7738, 7765]),)

In [108]:
from sklearn.naive_bayes import MultinomialNB

In [109]:
model = MultinomialNB()

In [110]:
model.fit(X_train_cv,y_train)

MultinomialNB()

In [111]:
x_test_cv = v.transform(X_test)

In [119]:
y_pred = model.predict(x_test_cv)

In [120]:
from sklearn.metrics import classification_report

In [122]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       988
           1       0.99      0.91      0.95       127

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [123]:
  emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [124]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [125]:

clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [126]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       988
           1       0.99      0.91      0.95       127

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

