<a href="https://colab.research.google.com/github/BALAJIHARIDASAN/Natural-Language-Processing/blob/main/Twitter_disaster_tweet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df_train = pd.read_csv('https://raw.githubusercontent.com/UditSharma9999/Natural_Language_Processing_with_Disaster_Tweets/main/data/train.csv')

In [ ]:
df_train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
df_test = pd.read_csv('https://raw.githubusercontent.com/UditSharma9999/Natural_Language_Processing_with_Disaster_Tweets/main/data/test.csv')

In [ ]:
df_test.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [ ]:
df_train= df_train[['text','target']]

In [ ]:
df_train.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [ ]:
import nltk
from nltk.corpus import stopwords
import re
import string
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# Let's apply stemming and stopwords on the data
stemmer = nltk.SnowballStemmer("english")
stopword = set(stopwords.words('english'))

In [ ]:
# Let's apply regex and do cleaning.
def data_cleaning(words):
    words = str(words).lower()
    words = re.sub('\[.*?\]', '', words)
    words = re.sub('https?://\S+|www\.\S+', '', words)
    words = re.sub('<.*?>+', '', words)
    words = re.sub('[%s]' % re.escape(string.punctuation), '', words)
    words = re.sub('\n', '', words)
    words = re.sub('\w*\d\w*', '', words)
    words = [word for word in words.split(' ') if words not in stopword]
    words=" ".join(words)
    words = [stemmer.stem(words) for word in words.split(' ')]
    words=" ".join(words)

    return words

In [ ]:
df_train.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [ ]:
df_train['text'] = df_train['text'].apply(data_cleaning)

In [ ]:
df_test['text'] = df_test['text'].apply(data_cleaning)

In [ ]:
df_train.head()

text  target
0  our deeds are the reason of this earthquake ma...       1
1  forest fire near la ronge sask canada forest f...       1
2  all residents asked to shelter in place are be...       1
3   people receive wildfires evacuation orders in...       1
4  just got sent this photo from ruby alaska as s...       1

In [ ]:
x = df_train['text']
y = df_train['target']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Lets do train-test split

x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 42)

print(len(x_train),len(y_train))
print(len(x_test),len(y_test))

5709 5709
1904 1904


In [ ]:
print(f"shape of X_train :{x_train.shape}")
print(f"shape of y_train :{y_train.shape}")
print(f"shape of X_test :{x_test.shape}")
print(f"shape of y_test :{y_test.shape}")

shape of X_train :(5709,)
shape of y_train :(5709,)
shape of X_test :(1904,)
shape of y_test :(1904,)


In [ ]:
# prompt: generate code for countvectorizer and svm

from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm

# Let's apply countvectorizer
vectorizer = CountVectorizer()
vectorizer.fit(x_train)
x_train = vectorizer.transform(x_train)
x_test = vectorizer.transform(x_test)

# Let's apply svm
clf = svm.SVC(kernel = 'linear', C = 1.0)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)


In [ ]:
# prompt: classification report and confusion matrix

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.78      0.80      0.79      1091
           1       0.72      0.70      0.71       813

    accuracy                           0.76      1904
   macro avg       0.75      0.75      0.75      1904
weighted avg       0.76      0.76      0.76      1904

[[874 217]
 [244 569]]


In [ ]:
# prompt: generate code with tfidf and svm

from sklearn.feature_extraction.text import TfidfVectorizer

x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 42)
# Let's apply tfidf
vectorizer = TfidfVectorizer()
vectorizer.fit(x_train)
x_train = vectorizer.transform(x_train)
x_test = vectorizer.transform(x_test)

# Let's apply svm
clf = svm.SVC(kernel = 'linear', C = 1.0)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.81      0.88      0.84      1091
           1       0.82      0.72      0.76       813

    accuracy                           0.81      1904
   macro avg       0.81      0.80      0.80      1904
weighted avg       0.81      0.81      0.81      1904

[[959 132]
 [228 585]]


In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
## Count unique Vocabulary
all_words = [word for sentence in df_train.text for word in sentence.split()]

unique_words = set(all_words)
# unique_words = (all_words)
vocab_size = len(unique_words)

print("Vocabulary Size:", vocab_size)

Vocabulary Size: 17155


In [ ]:
max_words = 50000
max_len = 300

x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 42)
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(x_train)

In [ ]:
sequences = tokenizer.texts_to_sequences(x_train)

In [ ]:
from keras.utils import pad_sequences
sequences_matrix = pad_sequences(sequences,maxlen=max_len)

In [ ]:
sequences_matrix

array([[ 2727,  1128,    19, ...,     7,   498,   914],
       [    0,     0,     0, ...,    20,  3008,  9319],
       [   25,    12,   428, ...,     2,    46,    10],
       ...,
       [    0,     0,     0, ...,  1028,  2587, 12207],
       [    8,     4,   590, ...,    43,  8060,  8061],
       [    0,     0,     0, ...,    13,    42,    58]], dtype=int32)

In [ ]:
from keras.models import Sequential
from keras.layers import LSTM, Embedding, Dense, SpatialDropout1D
from keras.optimizers import RMSprop

In [ ]:
#lstm
model = Sequential()
model.add(Embedding(max_words, 100, input_length = max_len))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100,dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation="sigmoid"))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 300, 100)          5000000   
                                                                 
 spatial_dropout1d_8 (Spati  (None, 300, 100)          0         
 alDropout1D)                                                    
                                                                 
 lstm_3 (LSTM)               (None, 100)               80400     
                                                                 
 dense_5 (Dense)             (None, 1)                 101       
                                                                 
Total params: 5080501 (19.38 MB)
Trainable params: 5080501 (19.38 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [ ]:
history = model.fit(sequences_matrix,y_train,batch_size=128,epochs = 5,validation_split=0.2)

Epoch 1/5
36/36 [==============================] - 41s 1s/step - loss: 0.6667 - accuracy: 0.6008 - val_loss: 0.5437 - val_accuracy: 0.7452
Epoch 2/5
36/36 [==============================] - 36s 979ms/step - loss: 0.5065 - accuracy: 0.7762 - val_loss: 0.5991 - val_accuracy: 0.7399
Epoch 3/5
36/36 [==============================] - 37s 1s/step - loss: 0.3869 - accuracy: 0.8518 - val_loss: 0.4687 - val_accuracy: 0.7977
Epoch 4/5
36/36 [==============================] - 36s 997ms/step - loss: 0.3614 - accuracy: 0.8783 - val_loss: 0.5075 - val_accuracy: 0.7977
Epoch 5/5
36/36 [==============================] - 36s 997ms/step - loss: 0.2574 - accuracy: 0.9137 - val_loss: 0.5972 - val_accuracy: 0.7811


In [ ]:
x_test

2644    so you have a new weapon that can cause unimag...
2227    the famping things i do for gishwhes just got ...
5448    dt georgegalloway rt  ‰ûïthe col police can ca...
132     aftershock back to school kick off was great i...
6845    in response to trauma children of addicts deve...
                              ...                        
5209    very glad that you got obliterated in x men fi...
387     mourning notices for stabbing arson victims st...
4848    mass murderer che guevara greeting a woman in ...
1032    womens flower printed shoulder handbags cross ...
7195    abcnews a nuclear bomb is a terrible weapon ab...
Name: text, Length: 1904, dtype: object

In [ ]:
test_sequences = tokenizer.texts_to_sequences(x_test)
test_sequences_matrix = pad_sequences(test_sequences,maxlen=max_len)

In [ ]:
# Model evaluation
accr = model.evaluate(test_sequences_matrix,y_test)

60/60 [==============================] - 5s 82ms/step - loss: 0.5810 - accuracy: 0.7904


In [ ]:
lstm_prediction = model.predict(test_sequences_matrix)

60/60 [==============================] - 5s 83ms/step


In [ ]:
lstm_prediction

array([[0.04180432],
       [0.111824  ],
       [0.94057465],
       ...,
       [0.9928341 ],
       [0.02655044],
       [0.9913628 ]], dtype=float32)

In [ ]:
res = []
for prediction in lstm_prediction:
    if prediction[0] < 0.5:
        res.append(0)
    else:
        res.append(1)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,res))

[[917 174]
 [225 588]]


In [ ]:
import keras
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
# Let's save the mdoel.
model.save("model.h5")

load_model=keras.models.load_model("model.h5")
with open('tokenizer.pickle', 'rb') as handle:
    load_tokenizer = pickle.load(handle)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
# Let's test our model on custom data.
test = 'crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz'

def clean_text(text):
    print(text)
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    print(text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text

test=[clean_text(test)]
print(test)

seq = load_tokenizer.texts_to_sequences(test)
padded = pad_sequences(seq, maxlen=300)
# print(seq)

pred = load_model.predict(padded)

print("pred", pred)
if pred<0.5:
    print("no hate")
else:
    print("hate and abusive")

crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
['cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz']
1/1 [==============================] - 0s 276ms/step
pred [[0.26442644]]
no hate


In [ ]:
#gru
from keras.models import Sequential
from keras.layers import LSTM, Embedding, Dense, SpatialDropout1D,GRU
from keras.optimizers import RMSprop
model = Sequential()
model.add(Embedding(max_words, 100, input_length = max_len))
model.add(SpatialDropout1D(0.2))
model.add(GRU(100,dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation="sigmoid"))
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 300, 100)          5000000   
                                                                 
 spatial_dropout1d_9 (Spati  (None, 300, 100)          0         
 alDropout1D)                                                    
                                                                 
 gru_2 (GRU)                 (None, 100)               60600     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 5060701 (19.31 MB)
Trainable params: 5060701 (19.31 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [ ]:
history = model.fit(sequences_matrix,y_train,batch_size=128,epochs = 5,validation_split=0.2)

Epoch 1/5
36/36 [==============================] - 37s 945ms/step - loss: 0.6787 - accuracy: 0.5706 - val_loss: 0.6718 - val_accuracy: 0.5595
Epoch 2/5
36/36 [==============================] - 49s 1s/step - loss: 0.5736 - accuracy: 0.6875 - val_loss: 0.5064 - val_accuracy: 0.7793
Epoch 3/5
36/36 [==============================] - 33s 929ms/step - loss: 0.4018 - accuracy: 0.8340 - val_loss: 0.4646 - val_accuracy: 0.7855
Epoch 4/5
36/36 [==============================] - 32s 883ms/step - loss: 0.3004 - accuracy: 0.8804 - val_loss: 0.4948 - val_accuracy: 0.7890
Epoch 5/5
36/36 [==============================] - 34s 907ms/step - loss: 0.2293 - accuracy: 0.9181 - val_loss: 0.5305 - val_accuracy: 0.7872


In [ ]:
test_sequences = tokenizer.texts_to_sequences(x_test)
test_sequences_matrix = pad_sequences(test_sequences,maxlen=max_len)
accr = model.evaluate(test_sequences_matrix,y_test)

60/60 [==============================] - 5s 85ms/step - loss: 0.5317 - accuracy: 0.7899


In [ ]:
GRU_prediction = model.predict(test_sequences_matrix)


60/60 [==============================] - 6s 89ms/step


In [ ]:
GRU_prediction

array([[0.01945923],
       [0.22048596],
       [0.55333835],
       ...,
       [0.9857179 ],
       [0.01296819],
       [0.895575  ]], dtype=float32)

In [ ]:
res = []
for prediction in GRU_prediction:
    if prediction[0] < 0.5:
        res.append(0)
    else:
        res.append(1)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test,res))

[[912 179]
 [221 592]]


In [ ]:
import keras
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
# Let's save the mdoel.
model.save("model1.h5")

load_model=keras.models.load_model("model1.h5")
with open('tokenizer.pickle', 'rb') as handle:
    load_tokenizer = pickle.load(handle)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
# Let's test our model on custom data.
test = 'crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz'

def clean_text(text):
    print(text)
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    print(text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text

test=[clean_text(test)]
print(test)

seq = load_tokenizer.texts_to_sequences(test)
padded = pad_sequences(seq, maxlen=300)
# print(seq)

pred = load_model.predict(padded)

print("pred", pred)
if pred<0.5:
    print("no hate")
else:
    print("hate and abusive")

crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
['cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz']
1/1 [==============================] - 0s 345ms/step
pred [[0.11818861]]
no hate


In [ ]:
#bidirectional lstm
from keras.models import Sequential
from keras.layers import LSTM, Embedding, Dense, SpatialDropout1D,GRU,Bidirectional
from keras.optimizers import RMSprop
model = Sequential()
model.add(Embedding(max_words, 100, input_length = max_len))
model.add(SpatialDropout1D(0.2))
model.add(Bidirectional(LSTM(100,dropout=0.2, recurrent_dropout=0.2)))
model.add(Dense(1, activation="sigmoid"))
model.summary()


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_10 (Embedding)    (None, 300, 100)          5000000   
                                                                 
 spatial_dropout1d_10 (Spat  (None, 300, 100)          0         
 ialDropout1D)                                                   
                                                                 
 bidirectional_1 (Bidirecti  (None, 200)               160800    
 onal)                                                           
                                                                 
 dense_7 (Dense)             (None, 1)                 201       
                                                                 
Total params: 5161001 (19.69 MB)
Trainable params: 5161001 (19.69 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

In [ ]:
history = model.fit(sequences_matrix,y_train,batch_size=128,epochs = 5,validation_split=0.2)

Epoch 1/5
36/36 [==============================] - 77s 2s/step - loss: 0.6814 - accuracy: 0.5715 - val_loss: 0.6339 - val_accuracy: 0.6471
Epoch 2/5
36/36 [==============================] - 69s 2s/step - loss: 0.5795 - accuracy: 0.7267 - val_loss: 0.5115 - val_accuracy: 0.7767
Epoch 3/5
36/36 [==============================] - 70s 2s/step - loss: 0.4378 - accuracy: 0.8266 - val_loss: 0.4787 - val_accuracy: 0.7907
Epoch 4/5
36/36 [==============================] - 70s 2s/step - loss: 0.3515 - accuracy: 0.8656 - val_loss: 0.4721 - val_accuracy: 0.7977
Epoch 5/5
36/36 [==============================] - 70s 2s/step - loss: 0.2850 - accuracy: 0.9045 - val_loss: 0.4806 - val_accuracy: 0.7898


In [ ]:
test_sequences = tokenizer.texts_to_sequences(x_test)
test_sequences_matrix = pad_sequences(test_sequences,maxlen=max_len)
accr = model.evaluate(test_sequences_matrix,y_test)

60/60 [==============================] - 9s 157ms/step - loss: 0.4780 - accuracy: 0.7941


In [ ]:
Bi_prediction = model.predict(test_sequences_matrix)

60/60 [==============================] - 9s 149ms/step


In [ ]:
Bi_prediction

array([[0.07258511],
       [0.22773352],
       [0.780596  ],
       ...,
       [0.9385544 ],
       [0.04155232],
       [0.9279023 ]], dtype=float32)

In [ ]:
res = []
for prediction in Bi_prediction:
    if prediction[0] < 0.5:
        res.append(0)
    else:
        res.append(1)

In [ ]:
print(confusion_matrix(y_test,res))

[[920 171]
 [221 592]]


In [ ]:
import keras
import pickle
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
# Let's save the mdoel.
model.save("model2.h5")

load_model=keras.models.load_model("model2.h5")
with open('tokenizer.pickle', 'rb') as handle:
    load_tokenizer = pickle.load(handle)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
# Let's test our model on custom data.
test = 'crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz'

def clean_text(text):
    print(text)
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    print(text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text

test=[clean_text(test)]
print(test)

seq = load_tokenizer.texts_to_sequences(test)
padded = pad_sequences(seq, maxlen=300)
# print(seq)

pred = load_model.predict(padded)

print("pred", pred)
if pred<0.5:
    print("no hate")
else:
    print("hate and abusive")

crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz crying out for more set me ablaz
['cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz cri set ablaz']
1/1 [==============================] - 1s 542ms/step
pred [[0.29326615]]
no hate
