In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.sample()

id                                              title  \
12883  12883  Half of German Women Feel Unsafe in Their Own ...   

                     author  \
12883  Donna Rachel Edmunds   

                                                    text  label  
12883  Nearly half of Germany’s women now feel unsafe...      0

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
###Drop Nan Values
df=df.dropna()


In [8]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [9]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [10]:
## Get the Dependent features
y=df['label']

In [11]:
X.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
import tensorflow as tf

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [15]:
### Vocabulary size
voc_size=7500

### Onehot Representation

In [26]:
messages=X.copy()

In [27]:
messages['title'][3]

'15 Civilians Killed In Single US Airstrike Have Been Identified'

In [28]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [19]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [29]:
messages.reset_index(inplace = True)

In [30]:
import nltk
import re
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer 

ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()
    
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [35]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [36]:
corpus[3]

'civilian kill singl us airstrik identifi'

In [37]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[3591, 4786, 474, 1277, 3439, 2936, 3698, 6053, 1421, 827],
 [6320, 1822, 2199, 3680, 1005, 5138, 5166],
 [4220, 3467, 2756, 4358],
 [2142, 3129, 1204, 2877, 1016, 3537],
 [6839, 1005, 3765, 1712, 3292, 1002, 1005, 5468, 5642, 5909],
 [7050,
  3005,
  1985,
  6593,
  5312,
  2407,
  2582,
  6404,
  2558,
  593,
  2153,
  1887,
  1377,
  3469,
  5166],
 [1410, 4376, 3839, 604, 3998, 6151, 5678, 3115, 3982, 2389, 3027],
 [1535, 3510, 4616, 2358, 4223, 2645, 2407, 2938, 3982, 2389, 3027],
 [5579, 3087, 4975, 2449, 7185, 2093, 6791, 7366, 2407, 2613],
 [5938, 765, 503, 4604, 4029, 1586, 809, 3275],
 [3994, 1896, 6865, 5501, 2755, 6119, 3230, 4076, 1689, 3709, 17],
 [2877, 5952, 3439, 2093, 2407, 4223],
 [5994, 1737, 3340, 6040, 239, 1265, 47, 3843, 2732],
 [56, 4201, 2009, 3550, 3677, 542, 12, 3982, 2389, 3027],
 [5548, 3718, 6805, 5478, 2031, 3982, 2389, 3027],
 [3608, 2874, 6677, 6598, 3538, 2090, 7424, 3386, 4455, 7159],
 [7057, 6415, 1822],
 [403, 5591, 4148, 853, 2407, 4596, 1077, 51

In [38]:
corpus[3]

'civilian kill singl us airstrik identifi'

In [39]:
onehot_repr[3]

[2142, 3129, 1204, 2877, 1016, 3537]

### Embedding Representation

In [40]:
sent_length=25
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 6053 1421  827]
 [   0    0    0 ... 1005 5138 5166]
 [   0    0    0 ... 3467 2756 4358]
 ...
 [   0    0    0 ... 3982 2389 3027]
 [   0    0    0 ... 7356 6089 5744]
 [   0    0    0 ... 6586  473 4998]]


In [41]:
embedded_docs[3]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0, 2142, 3129, 1204,
       2877, 1016, 3537], dtype=int32)

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 3591, 4786,  474, 1277, 3439, 2936, 3698,
       6053, 1421,  827], dtype=int32)

In [44]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 25, 40)            300000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 356,501
Trainable params: 356,501
Non-trainable params: 0
_________________________________________________________________
None


In [45]:
len(embedded_docs),y.shape

(18285, (18285,))

In [46]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [47]:
X_final.shape,y_final.shape

((18285, 25), (18285,))

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=15)

### Model Training

In [49]:

model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=25)

Epoch 1/25
458/458 [==============================] - 11s 8ms/step - loss: 0.2613 - accuracy: 0.8834 - val_loss: 0.1710 - val_accuracy: 0.9281
Epoch 2/25
458/458 [==============================] - 3s 6ms/step - loss: 0.1247 - accuracy: 0.9519 - val_loss: 0.1734 - val_accuracy: 0.9292
Epoch 3/25
458/458 [==============================] - 3s 6ms/step - loss: 0.0745 - accuracy: 0.9742 - val_loss: 0.1978 - val_accuracy: 0.9311
Epoch 4/25
458/458 [==============================] - 3s 6ms/step - loss: 0.0430 - accuracy: 0.9860 - val_loss: 0.2519 - val_accuracy: 0.9221
Epoch 5/25
458/458 [==============================] - 3s 6ms/step - loss: 0.0234 - accuracy: 0.9930 - val_loss: 0.3168 - val_accuracy: 0.9229
Epoch 6/25
458/458 [==============================] - 3s 6ms/step - loss: 0.0137 - accuracy: 0.9965 - val_loss: 0.3786 - val_accuracy: 0.9177
Epoch 7/25
458/458 [==============================] - 3s 6ms/step - loss: 0.0075 - accuracy: 0.9978 - val_loss: 0.4552 - val_accuracy: 0.9182
Epoch

### Adding Dropout 

In [50]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [51]:
y_pred=model.predict(X_test)

115/115 [==============================] - 1s 2ms/step


In [57]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [58]:
from sklearn.metrics import confusion_matrix

In [59]:
confusion_matrix(y_test,y_pred)

array([[2117,    0],
       [1540,    0]])

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5788898003828274

In [61]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.58      1.00      0.73      2117
           1       0.00      0.00      0.00      1540

    accuracy                           0.58      3657
   macro avg       0.29      0.50      0.37      3657
weighted avg       0.34      0.58      0.42      3657



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
