In [40]:
import pandas as pd

In [41]:
df=pd.read_csv('train.csv')

In [42]:
df.sample()

id                                              title author  \
15301  15301  News: First Steps: Donald Trump Has To Go Arou...    NaN   

                                                    text  label  
15301  Email \nDonald Trump’s inauguration may be mon...      1

In [43]:
df.shape

(20800, 5)

In [44]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [45]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [46]:
###Drop Nan Values
df=df.dropna()


In [47]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [48]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [49]:
## Get the Dependent features
y=df['label']

In [50]:
X.shape

(18285, 4)

In [51]:
y.shape

(18285,)

In [52]:
import tensorflow as tf

In [53]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Bidirectional
from tensorflow.keras.layers import Dense

In [54]:
### Vocabulary size
voc_size=7500

### Onehot Representation

In [55]:
messages=X.copy()

In [56]:
messages['title'][3]

'15 Civilians Killed In Single US Airstrike Have Been Identified'

In [57]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [58]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [59]:
messages.reset_index(inplace = True)

In [60]:
import nltk
import re
from nltk.corpus import stopwords

In [61]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [62]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer 

ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()
    
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [63]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [64]:
corpus[3]

'civilian kill singl us airstrik identifi'

In [65]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[6531, 2715, 902, 3731, 235, 4262, 3960, 3312, 2598, 4443],
 [6350, 5951, 6673, 3520, 5663, 2444, 128],
 [2754, 4424, 3314, 7092],
 [7073, 3930, 2254, 1223, 1293, 6046],
 [4680, 5663, 6676, 2192, 1062, 280, 5663, 465, 5794, 1738],
 [5852,
  2661,
  109,
  2259,
  942,
  4030,
  3174,
  3821,
  7038,
  3061,
  5039,
  868,
  5533,
  7203,
  128],
 [232, 3378, 2475, 3990, 3945, 864, 3967, 4792, 7460, 6067, 4462],
 [20, 3164, 1347, 2746, 4727, 1199, 4030, 4927, 7460, 6067, 4462],
 [1363, 1504, 4159, 814, 5633, 2937, 6017, 3691, 4030, 668],
 [1749, 5928, 1419, 6711, 2864, 6044, 255, 4889],
 [4293, 1108, 4479, 4289, 6164, 1302, 898, 890, 7402, 6557, 1771],
 [1223, 6277, 235, 2937, 4030, 4727],
 [4185, 2267, 707, 2126, 7102, 551, 7139, 1946, 6565],
 [4041, 2874, 4184, 5465, 6482, 1172, 4411, 7460, 6067, 4462],
 [2550, 3068, 4919, 4034, 6337, 7460, 6067, 4462],
 [2449, 312, 1454, 3303, 1071, 7252, 2377, 3993, 5253, 4585],
 [3835, 1438, 5951],
 [2420, 892, 1336, 2493, 4030, 3372, 6440, 128],


In [66]:
corpus[3]

'civilian kill singl us airstrik identifi'

In [67]:
onehot_repr[3]

[7073, 3930, 2254, 1223, 1293, 6046]

### Embedding Representation

In [68]:
sent_length=25
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3312 2598 4443]
 [   0    0    0 ... 5663 2444  128]
 [   0    0    0 ... 4424 3314 7092]
 ...
 [   0    0    0 ... 7460 6067 4462]
 [   0    0    0 ... 3144 1295 6007]
 [   0    0    0 ... 1986 3620 6651]]


In [69]:
embedded_docs[3]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0, 7073, 3930, 2254,
       1223, 1293, 6046], dtype=int32)

In [70]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 6531, 2715,  902, 3731,  235, 4262, 3960,
       3312, 2598, 4443], dtype=int32)

In [71]:
embedding_vector_features=20
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 25, 20)            150000    
                                                                 
 bidirectional_1 (Bidirectio  (None, 200)              96800     
 nal)                                                            
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 247,001
Trainable params: 247,001
Non-trainable params: 0
_________________________________________________________________
None


In [72]:
len(embedded_docs),y.shape

(18285, (18285,))

In [73]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [74]:
X_final.shape,y_final.shape

((18285, 25), (18285,))

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=15)

### Model Training

In [76]:

model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=15)

Epoch 1/15
458/458 [==============================] - 8s 11ms/step - loss: 0.2611 - accuracy: 0.8828 - val_loss: 0.1781 - val_accuracy: 0.9292
Epoch 2/15
458/458 [==============================] - 4s 9ms/step - loss: 0.1303 - accuracy: 0.9504 - val_loss: 0.1894 - val_accuracy: 0.9253
Epoch 3/15
458/458 [==============================] - 4s 9ms/step - loss: 0.0937 - accuracy: 0.9670 - val_loss: 0.1904 - val_accuracy: 0.9229
Epoch 4/15
458/458 [==============================] - 4s 9ms/step - loss: 0.0684 - accuracy: 0.9776 - val_loss: 0.2241 - val_accuracy: 0.9204
Epoch 5/15
458/458 [==============================] - 4s 9ms/step - loss: 0.0492 - accuracy: 0.9839 - val_loss: 0.2657 - val_accuracy: 0.9155
Epoch 6/15
458/458 [==============================] - 4s 9ms/step - loss: 0.0307 - accuracy: 0.9892 - val_loss: 0.3137 - val_accuracy: 0.9204
Epoch 7/15
458/458 [==============================] - 4s 9ms/step - loss: 0.0228 - accuracy: 0.9930 - val_loss: 0.3675 - val_accuracy: 0.9202
Epoch

### Adding Dropout 

In [77]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.2))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [78]:
y_pred=model.predict(X_test)

115/115 [==============================] - 1s 3ms/step


In [79]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [80]:
from sklearn.metrics import confusion_matrix

In [81]:
confusion_matrix(y_test,y_pred)

array([[1003, 1114],
       [ 250, 1290]])

In [82]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6270166803390758

In [83]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.47      0.60      2117
           1       0.54      0.84      0.65      1540

    accuracy                           0.63      3657
   macro avg       0.67      0.66      0.62      3657
weighted avg       0.69      0.63      0.62      3657

