In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['Break long paragraphs up',
        'Go really short when you want to make a point',
        ' Shorten your sentence length',
        ' Review your word choices',
        'Use rhythm to guide your paragraphs',
        ' Look at your paragraphs on the page']

In [3]:
### Vocabulary size
voc_size=5000

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[563, 194, 4725, 1038], [2883, 1890, 4355, 1682, 3217, 3954, 1123, 3866, 970, 1074], [1077, 1703, 1380, 3033], [2660, 1703, 861, 4852], [1660, 602, 1123, 4947, 1703, 4725], [654, 2058, 1703, 4725, 4764, 4332, 4727]]


In [5]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)  # padding - to make the length of sentence equal pre/post
print(embedded_docs)

[[   0    0    0    0  563  194 4725 1038]
 [4355 1682 3217 3954 1123 3866  970 1074]
 [   0    0    0    0 1077 1703 1380 3033]
 [   0    0    0    0 2660 1703  861 4852]
 [   0    0 1660  602 1123 4947 1703 4725]
 [   0  654 2058 1703 4725 4764 4332 4727]]


In [8]:
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             50000     
                                                                 
Total params: 50,000
Trainable params: 50,000
Non-trainable params: 0
_________________________________________________________________


In [11]:

print(model.predict(embedded_docs))

1/1 [==============================] - 0s 198ms/step
[[[ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769
   -0.029937    0.01082467  0.0157369  -0.03892486  0.00391134]
  [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769
   -0.029937    0.01082467  0.0157369  -0.03892486  0.00391134]
  [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769
   -0.029937    0.01082467  0.0157369  -0.03892486  0.00391134]
  [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769
   -0.029937    0.01082467  0.0157369  -0.03892486  0.00391134]
  [ 0.02848497 -0.04478815 -0.00787759 -0.04837709 -0.00302554
    0.04384719  0.00420836  0.0173905  -0.00799055  0.00057813]
  [ 0.03459257  0.02794509 -0.0457828   0.01435025  0.04345102
    0.00080516 -0.00526411  0.04906389  0.03402754 -0.01290816]
  [-0.02329744  0.03545168 -0.02090802 -0.03869624  0.0320352
    0.00474415  0.03409051  0.03700734  0.03191486 -0.02481799]
  [ 0.04916606  0.03700053  0.0141595  -0.03521776  0.03446

In [12]:

embedded_docs[0]

array([   0,    0,    0,    0,  563,  194, 4725, 1038], dtype=int32)

In [13]:

print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 35ms/step
[[ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769 -0.029937
   0.01082467  0.0157369  -0.03892486  0.00391134]
 [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769 -0.029937
   0.01082467  0.0157369  -0.03892486  0.00391134]
 [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769 -0.029937
   0.01082467  0.0157369  -0.03892486  0.00391134]
 [ 0.04243721  0.01819248 -0.03239085  0.03694875  0.02102769 -0.029937
   0.01082467  0.0157369  -0.03892486  0.00391134]
 [ 0.02848497 -0.04478815 -0.00787759 -0.04837709 -0.00302554  0.04384719
   0.00420836  0.0173905  -0.00799055  0.00057813]
 [ 0.03459257  0.02794509 -0.0457828   0.01435025  0.04345102  0.00080516
  -0.00526411  0.04906389  0.03402754 -0.01290816]
 [-0.02329744  0.03545168 -0.02090802 -0.03869624  0.0320352   0.00474415
   0.03409051  0.03700734  0.03191486 -0.02481799]
 [ 0.04916606  0.03700053  0.0141595  -0.03521776  0.03446415 -0.02255179
  -0.01