In [1]:
from keras.datasets import imdb
from keras import preprocessing
from keras.models import Sequential
from keras.layers import Flatten, Dense, Embedding
from keras.utils import pad_sequences
import keras

In [2]:
max_feature = 10000
maxlen = 20


(x_train,y_train),(x_test,y_test) = imdb.load_data(num_words = 10000)

17464789/17464789 [==============================] - 2s 0us/step


In [3]:
x_train = keras.utils.data_utils.pad_sequences (x_train,maxlen= maxlen)
x_test = keras.utils.data_utils.pad_sequences (x_test,maxlen= maxlen)

In [4]:
model = Sequential()
model.add(Embedding(1000,8,input_length=maxlen))
model.add(Flatten())
model.add(Dense(1,activation= 'sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 8)             8000      
                                                                 
 flatten (Flatten)           (None, 160)               0         
                                                                 
 dense (Dense)               (None, 1)                 161       
                                                                 
Total params: 8,161
Trainable params: 8,161
Non-trainable params: 0
_________________________________________________________________


In [5]:
x_train

array([[  65,   16,   38, ...,   19,  178,   32],
       [  23,    4, 1690, ...,   16,  145,   95],
       [1352,   13,  191, ...,    7,  129,  113],
       ...,
       [  11, 1818, 7561, ...,    4, 3586,    2],
       [  92,  401,  728, ...,   12,    9,   23],
       [ 764,   40,    4, ...,  204,  131,    9]], dtype=int32)

In [6]:
x_train[0]

array([  65,   16,   38, 1334,   88,   12,   16,  283,    5,   16, 4472,
        113,  103,   32,   15,   16, 5345,   19,  178,   32], dtype=int32)

In [7]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [8]:
x_test

array([[ 286,  170,    8, ...,   14,    6,  717],
       [  10,   10,  472, ...,  125,    4, 3077],
       [  34,    2,   45, ...,    9,   57,  975],
       ...,
       [ 226,   20,  272, ...,   21,  846, 5518],
       [  55,  117,  212, ..., 2302,    7,  470],
       [  19,   14,   20, ...,   34, 2005, 2643]], dtype=int32)

In [9]:
y_test

array([0, 1, 1, ..., 0, 0, 0])

In [10]:
model.compile(optimizer= 'rmsprop',loss = 'binary_crossentropy',metrics = ['accuracy'])


In [11]:
model.fit(x_train,y_train,epochs = 15)

Epoch 1/15
782/782 [==============================] - 5s 3ms/step - loss: 0.6594 - accuracy: 0.6338
Epoch 2/15
782/782 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7340
Epoch 3/15
782/782 [==============================] - 3s 3ms/step - loss: 0.4997 - accuracy: 0.7523
Epoch 4/15
782/782 [==============================] - 3s 3ms/step - loss: 0.4871 - accuracy: 0.7599
Epoch 5/15
782/782 [==============================] - 3s 3ms/step - loss: 0.4788 - accuracy: 0.7650
Epoch 6/15
782/782 [==============================] - 3s 3ms/step - loss: 0.4711 - accuracy: 0.7713
Epoch 7/15
782/782 [==============================] - 2s 3ms/step - loss: 0.4631 - accuracy: 0.7772
Epoch 8/15
782/782 [==============================] - 3s 4ms/step - loss: 0.4551 - accuracy: 0.7810
Epoch 9/15
782/782 [==============================] - 3s 4ms/step - loss: 0.4469 - accuracy: 0.7889
Epoch 10/15
782/782 [==============================] - 3s 3ms/step - loss: 0.4397 - accuracy: 0.7934

In [13]:
y_pred=model.predict(x_test)

782/782 [==============================] - 1s 1ms/step


In [15]:
import numpy as np
y_pred=np.where(y_pred > 0.5, 1,0)

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
confusion_matrix(y_test,y_pred)

array([[8750, 3750],
       [3232, 9268]])

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.72072

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.73      0.70      0.71     12500
           1       0.71      0.74      0.73     12500

    accuracy                           0.72     25000
   macro avg       0.72      0.72      0.72     25000
weighted avg       0.72      0.72      0.72     25000

